CREATE DATABASE SHOOT_ADV
ON ( 
NAME = N'AdventureWorks2008R2_Data',
FIlENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\SHOOTADV.ss'
) AS SNAPSHOT OF AdventureWorks2008R2
GO